### ISSUE TITLE
Complex accept header throws "Error translating between RDF formats"

### ISSUE THREAD

**Issue by rubensworks** [nodeSolidServer/node-solid-server#1618]
When requesting a simple document such as
```
<ex:s> <ex:p> <ex:o>.
```
with the complex accept header `application/n-quads,application/trig;q=0.95,application/ld+json;q=0.9,application/n-triples;q=0.8,text/turtle;q=0.6,application/rdf+xml;q=0.5,application/json;q=0.45,text/n3;q=0.35,application/xml;q=0.3,image/svg+xml;q=0.3,text/xml;q=0.3,text/html;q=0.2,application/xhtml+xml;q=0.18` throws the following error:
```
Error translating between RDF formats
```

**Comment by jeff-zucker** [comment]
AFAIK, this issue prevents comunica-solid from being used on NSS, a huge loss.

**Comment by TallTed** [comment]
I wonder, is anyone able to test by requesting that simple document with simple `Accept:` headers, one request for each format, to see which lead to that error?

This should help narrow the focus towards a fix, or at least, a better understanding.

**Comment by jeff-zucker** [comment]
I am going from this section of https://github.com/comunica/comunica-feature-solid/tree/master/engines/query-sparql-solid#readme

> Querying or updating existing documents fails with the error Error translating between RDF formats (https://github.com/nodeSolidServer/node-solid-server/issues/1618). Creating new documents does work.

**Comment by TallTed** [comment]
Searching this repo for "Error translating between RDF formats" finds a number of Issues and even PRs. At least one suggests that Comunica adding `*/*;q=0.001` to the `Accept:` header would be a workaround. Finding the *real* issue and thereby the *real* solution requires [the experiment I suggested above](https://github.com/nodeSolidServer/node-solid-server/issues/1618#issuecomment-2168563465).

My guess is that NSS is using an external library to translate RDF formats, and it's treating the `<ex:s> <ex:p> <ex:o>.` as a format which is less preferred than another, to which that external library *shuld* be able to translate the `<ex:s> <ex:p> <ex:o>.` — which translation is failing, due to an apparent bug in that external library.

If NSS uses internal code for such serialization translations, all the better, as whatever is found to be the problem translation should be directly fixable.

I also wonder what serialization NSS is deciding that `<ex:s> <ex:p> <ex:o>.` is. It may be that this serialization should simply be delivered to Comunica without translation, even though NSS and/or its helper library *think* they can translate it from whatever serialization Comunica thinks it is to a serialization with a higher calculated `quality`...

All that said, I would really like it if NSS could output more detail than "Error translating between RDF formats". Minimally I'd like to see identification of both the existing input format, and the target output format. If it is possible to also output the text of the exact line of whatever document (as they won't always be one-liners), including its line number, these would help users fix the issue in their environment.

**Comment by csarven** [comment]
What might be the request URI? I wasn't able to reproduce this error. Anyone else?

**Comment by rubensworks** [comment]
Given that this issue was posted 3 years ago, the problem may have very well been fixed by now. I haven't tested comunica over NSS since then.

I can do another test soon to see if I can reproduce it again.

**Comment by rubensworks** [comment]
I just tested it again, and things seem to be working correctly now! 🎉 
It can be tested here: https://query.comunica.dev/#datasources=https%3A%2F%2Frubensworks.solidcommunity.net%2Fpublic%2Ftest.ttl&query=SELECT%20*%20WHERE%20%7B%0A%20%20%3Fs%20%3Fp%20%3Fo.%0A%7D
