### ISSUE TITLE
who maintains NSS?

### ISSUE THREAD

**Issue by melvincarvalho** [nodeSolidServer/node-solid-server#1740]
I've been trying to figure this out since january 2023

![image](https://github.com/nodeSolidServer/node-solid-server/assets/65864/0e2b347c-3fcd-4ca7-a1ec-4d715d75d630)

Can anyone help with the answer?

**Comment by melvincarvalho** [comment]
Can anyone answer this?  Is the project still alive?

**Comment by NoelDeMartin** [comment]
I certainly don't maintain it so take my opinion with a grain of salt, and hopefully someone else can confirm it.

But I would say @bourgeoa is the only one maintaining it at this point. I know @timea-solid and @angelo-v are also familiar with the codebase and have done something at some point, but I'm not sure how involved they are at the moment (maybe they can confirm it).

I'm also not completely sure where NSS's maintainability ends and other projects' begins, like [mashlib](https://github.com/SolidOS/mashlib), [solidos](https://github.com/SolidOS/solidos/), [solid-ui](https://github.com/SolidOS/solid-ui/), etc. But this shouldn't be a controversial or unanswerable question, just look at the [contributor graphs](https://github.com/nodeSolidServer/node-solid-server/graphs/contributors) of all the related projects and you can see who is actually maintaining it (regardless of what anyone says).

I want to clarify that I'm not blaming anyone for lack of contributons though. Because as [we discussed on a recent SolidOS meeting](https://solidos.solidcommunity.net/public/SolidOS%20team%20meetings/2023/2023_10_25.md), there is no funding or any type of support for this project. So whoever chooses to work on it, does it on a purely voluntary basis. And I suppose that's the real problem here. I agree we need a "community-led" Solid server, but if there is no to financial backing for anyone to actually do it... that's just how things turn out.

**Comment by melvincarvalho** [comment]
Please can someone answer the question in the issue.  The link provided is not available to the public.  I have been asking for over 9 months.

**Comment by melvincarvalho** [comment]
> So whoever chooses to work on it, does it on a purely voluntary basis

They dont though.  It's an absolutely closed club, non transparent, and not even after 9 months visible to the public.  It's a black box to anyone that wants to use it or contribute to it.

I was directed to this 9 months ago:

https://github.com/orgs/nodeSolidServer/teams

And it says "You’re not a member of any teams in this organization." and redirects me.

https://github.com/bourgeoa

![image](https://github.com/nodeSolidServer/node-solid-server/assets/65864/a5bac3c9-07ec-43aa-b97c-d464f85c26db)

I understand alain may be sick lately, and I wish him the best of health.

But clearly others do have commit access.  And a once vibrant project is now a ghost town.  Please can we have transparency and maybe a new team, here.

**Comment by Otto-AA** [comment]
I think @NoelDeMartin already perfectly answered your question, but I'll try to be clearer by citing the meeting notes:

> [...] What makes CSS better than NSS, then? [...]
> The reason is that there is nobody maintaining NSS. If we don't implement the notifications spec, it won't be usable.

It is not maintained. There are some thankworthy bug fixes and version updates by @bourgeoa , but nonetheless the project is far from being alive. New features haven't been implemented, and eg the [critical security issue](https://github.com/nodeSolidServer/node-solid-server/issues/1719) I've reported hasn't been tackled either for half a year.

I totally agree with @NoelDeMartin that nobody should be blamed for this. This is just the current state of a project based on voluntary contributions. Reading the SolidOS meeting notes, people are also thinking about what this means for the future of NSS.

> Please can we have transparency and maybe a new team, here.

While I didn't join the [public SolidOS meetings](https://solidos.solidcommunity.net/Team/team%20meetings/schedule.html), reading their [public notes](https://solidos.solidcommunity.net/public/SolidOS%20team%20meetings/2023/2023_10_25.md) suggests that there are no resources for a new team. If you really want a new team, then I kindly suggest you to find a structure in which the team gets paid, or to find a way to attract more and consistent voluntary contributions. Just asking for a new team won't help.

And sorry if my tone was slightly annoyed, but I got annoyed by the way you require answers from volunteers. This is not a support center backed by commercial interests, it's a place where the community tries to work together.

**Comment by timbl** [comment]
@melvincarvalho Your question was answered well by @NoelDeMartin by pointing to the [NSS contributor graphs](https://github.com/nodeSolidServer/node-solid-server/graphs/contributors). You see that recently it has been @bourgeoa who has done the work of keeping making maintenance releases.   He has done that with the moral support and huge thanks of those in the SolidOS team who rely on the servers to work.  You have a mail thread about this which maintains which suggests that the questioned is still unanswered. 

@bourgeoa stepped in when he saw (around 4 years ago) that the planned rapid transition from NSS to CSS, a complete re-write on NSS) was at risk due to CSS taking longer.   But that is the stuff of other issues in NSS and CSS and  [solidcommunity.net#62](https://github.com/solid/solidcommunity.net/issues/62)

I suggest closing this issue as the answer is, recently, @bourgeoa .
