### ISSUE TITLE
Consider adding Accept-Post and Accept-Put

### ISSUE THREAD

**Issue by RubenVerborgh** [nodeSolidServer/node-solid-server#935]

**Comment by RubenVerborgh** [comment]
To be determined: does this depend on auth status?

**Comment by dmitrizagidulin** [comment]
Is this not already handled by the WAC-Allow: header?

**Comment by RubenVerborgh** [comment]
No; WAC-Allow indicates what the agent is able to do, whereas the Accept-* headers indicate what media types cam be sent.

**Comment by dmitrizagidulin** [comment]
Ahh, ok, got it.

**Comment by namedgraph** [comment]
What's the rationale for more non-standard headers when plain `Accept` is enough?

**Comment by csarven** [comment]
@namedgraph FYI, this issue was derived from https://github.com/solid/node-solid-server/issues/931 . Usually leaving some provenance helps future readers.

Accept is too broad in context of OPTIONS. Not to mention that it'll probably interpreted for the OPTIONS itself.

For each method, it is useful to distinguish between acceptable mimetypes. Unless a server is capable of handling the same values for each allowed method, then sure, Accept alone would be sufficient, in theory. Even then, I don't think that's a good idea. There is also no evidence that a LD server that Accepts text/html is going to take on a PATCH with text/html - just to take an example. Take my word for it ;)

There is sufficient "standard" talk re Accept-Post and Accept-Patch. Accept-Put doesn't ( also mentioned in https://github.com/solid/node-solid-server/issues/931#issuecomment-438599790 ). It doesn't matter. Just implement something that's sufficiently aligned with other stuff - consider it as incubation - and then bump it up to standards given that there was some experimentation and experience.

**Comment by kjetilk** [comment]
I think we should start using RDF more, so that we can have in-band semantics... :-)  Perhaps a `.controls` resource or something. This isn't my primary use case for it, but headers are starting to get pretty verbose.

**Comment by csarven** [comment]
@namedgraph Why every response? Send only when responding to OPTIONS.

**Comment by namedgraph** [comment]
@kjetilk not so simple. First you would need semantics of what `.controls` means and how it is discoverable.

**Comment by csarven** [comment]
AFAICT, this issue is resolved at the very least by PR: https://github.com/nodeSolidServer/node-solid-server/pull/1754
